// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoe7Fu2tWBYxgQJP0ttNneAQ4cYaCEP-M',
    appId: '1:764604899770:web:fcffda0746f0b74ad37d83',
    messagingSenderId: '764604899770',
    projectId: 'keysapp-97218',
    authDomain: 'keysapp-97218.firebaseapp.com',
    storageBucket: 'keysapp-97218.appspot.com',
    measurementId: 'G-N52FCRS2X1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOBezeFgllgeRDOL-SEPCyuj62fwvBdVQ',
    appId: '1:764604899770:android:4410713c28b8c9bfd37d83',
    messagingSenderId: '764604899770',
    projectId: 'keysapp-97218',
    storageBucket: 'keysapp-97218.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb9GQqTSD-bELy-yHldFhYLTVN-ahnISk',
    appId: '1:764604899770:ios:82c7b958764cffb6d37d83',
    messagingSenderId: '764604899770',
    projectId: 'keysapp-97218',
    storageBucket: 'keysapp-97218.appspot.com',
    iosBundleId: 'com.example.keys',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb9GQqTSD-bELy-yHldFhYLTVN-ahnISk',
    appId: '1:764604899770:ios:f0e5c9dcc13a2896d37d83',
    messagingSenderId: '764604899770',
    projectId: 'keysapp-97218',
    storageBucket: 'keysapp-97218.appspot.com',
    iosBundleId: 'com.example.keys.RunnerTests',
  );
}
